kalatheme.settings:
  type: theme_settings
  label: 'Kalatheme settings'
  mapping:
    kalatheme_framework:
      type: string
    kalatheme_viewport:
      type: string
    kalatheme_bootstrap_enable_cdn:
      type: boolean
    kalatheme_bootstrap_cdn_css:
      type: string
    kalatheme_bootstrap_cdn_js:
      type: string
    kalatheme_fontawesome_enable:
      type: boolean
    kalatheme_fontawesome_cdn:
      type: string
    kalatheme_foundationicon_enable:
      type: boolean
    kalatheme_foundationicon_cdn:
      type: string
